#!/bin/sh

antibody_compile() {
  echo "Removing zcompdump..."
  rm -f $ZDOTDIR/.zcompdump
  echo "Recompiling antibody plugins..."
  antibody bundle < $ZDOTDIR/plugins > $ZDOTDIR/.plugins.sh
  echo "Finished!"
}

antibody_load() {
  # If plugins.sh does not exist, or if plugins is more recent
  # than plugins.sh, recompile plugins
  if [[ ! -f $ZDOTDIR/.plugins.sh ]]; then
    antibody_compile
  elif [[ $ZDOTDIR/.plugins.sh -ot $ZDOTDIR/plugins ]]; then
    antibody_compile
  fi
}


# export ZSH="$(antibody home)/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"

antibody_load
