#!/usr/bin/env sh

# get colors from pywal
source $HOME/.cache/wal/colors-yabai.sh

spacebar -m config height             22
spacebar -m config position           top
spacebar -m config text_font          "Tamzen Nerd Font:Medium:14.0"
spacebar -m config icon_font          "Tamzen Nerd Font:Medium:14.0"
spacebar -m config background_color   $background
spacebar -m config foreground_color   $foreground
# spacebar -m config space_icon_strip 1 2 3 4 5 6 7 8 9 10

# spacebar -m config power_icon_strip

# spacebar -m config space_icon        

# spacebar -m config clock_icon        

spacebar -m config clock_format      "%a %d %b %R"

echo "spacebar configuration loaded.."
