#!/usr/bin/env bash

# get colors from pywal
source $HOME/.cache/wal/colors-yabai.sh


# Nerd Font Icon names in shell
for file in ~/.local/share/fonts/*.sh; do
  if [[ -f "$file" ]] && [[ -f "$file" ]]; then
    source "$file"
  fi
done



height=22
position=top

spacebar -m config height             $height
spacebar -m config position           $position
spacebar -m config spacing_left       15
spacebar -m config text_font          "Tamzen Nerd Font:Medium:14.0"
spacebar -m config icon_font          "Tamzen Nerd Font:Medium:14.0"
spacebar -m config background_color   $background
spacebar -m config foreground_color   $color3
# spacebar -m config space_icon_strip 

# spacebar -m config power_icon_strip

spacebar -m config space_icon_strip   $i_mdi_numeric_1_box \
                                      $i_mdi_numeric_2_box \
                                      $i_mdi_numeric_3_box \
                                      $i_mdi_numeric_4_box \
                                      $i_mdi_numeric_5_box \
                                      $i_mdi_numeric_6_box \
                                      $i_mdi_numeric_7_box \
                                      $i_mdi_numeric_8_box \
                                      $i_mdi_numeric_9_box

# spacebar -m config clock_icon        

spacebar -m config clock_format      "%a %d %b %R"

echo "spacebar configuration loaded.."


if [[ "$position" == "bottom" ]]; then
  echo "yabai config for bottom"
  yabai -m config external_bar all:0:$height
else
  echo "yabai config for top"
  yabai -m config external_bar all:$height:0
fi

