#!/usr/bin/env bash

# get color values from pywal
source $HOME/.cache/wal/colors.sh

# yabai template colours
CBACK=$(echo $background | sed 's/#//')
CFORE=$(echo $foreground | sed 's/#//')
CACTV=$(echo $color3 | sed 's/#//')
CNORM=$(echo $color1 | sed 's/#//')
CINSE=$(echo $foreground | sed 's/#//')

limelight -m config debug_output on
limelight -m config width 1
limelight -m config radius 0
limelight -m config placement interior
limelight -m config active_color "AA${CFORE}"
# limelight -m config normal_color "AA${CBACK}"
