#!/usr/bin/env bash

export XDG_CURRENT_DESKTOP=bspwm

# Set wallpaper
$HOME/.fehbg

# Fixes IntelliJ gray screen issue
export _JAVA_AWT_WM_NONREPARENTING=1

# Fix Java programs that assume they are in a reparenting window manager
wmname LG3D

bspc monitor primary -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config automatic_scheme     alternate
bspc config removal_adjustment   true

bspc config ignore_ewmh_focus true

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors false

if pgrep sxhkd; then
  pkill -USR1 sxhkd;
else
  nohup sxhkd &
fi

$HOME/.config/polybar/launch
