
[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '0x1c1e26'
foreground = '0xe0e0e0'

[colors.normal]
black = '0x16161c'
red = '0xe95678'
green = '0x29d398'
yellow = '0xfab795'
blue = '0x26bbd9'
magenta = '0xee64ac'
cyan = '0x59e1e3'
white = '0xd5d8da'

[colors.bright]
black = '0x5b5858'
red = '0xec6a88'
green = '0x3fdaa4'
yellow = '0xfbc3a7'
blue = '0x3fc4de'
magenta = '0xf075b5'
cyan = '0x6be4e6'
white = '0xd5d8da'

[cursor]
style = "Block"

[font]
builtin_box_drawing = true
size = 16

[font.normal]
family = "ProggyClean Nerd Font"

[scrolling]
history = 100000
multiplier = 3

[window]
blur = true
decorations = "none"
dynamic_padding = true
padding = { x = 6, y = 7 }
opacity = 1.0
startup_mode = "Windowed"

[general]
ipc_socket = true
