#!/usr/bin/env bash

if pgrep polybar; then
  polybar-msg cmd quit
fi

echo "---" | tee -a /tmp/polybar.log > /dev/null

for monitor in $(polybar --list-monitors | cut -d':' -f1); do
  MONITOR="${monitor}" polybar standard &> /tmp/polybar.log &
done
