[aws]
symbol = " "
disabled = true

[battery]
disabled = true

[character]
success_symbol  = "[](bold green)"
error_symbol    = "[](bold red)"
vicmd_symbol    = "[](bold green)"

[dart]
symbol = " "

[directory]
read_only = "  "

[docker_context]
symbol = "  "
disabled = false
only_with_files = false

[git_branch]
symbol = " "

[gcloud]
disabled = true

[golang]
symbol = ""

[java]
disabled = true
symbol = " "

[memory_usage]
symbol = "  "

[nodejs]
symbol = " "
disabled = true

[package]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = " "

[terraform]
disabled = true

[env_var]
variable = "SPRING_PROFILES_ACTIVE"
style = "bold yellow"
format = "using [$env_value]($style) "

# [[env_var]]
# variable = "NEO4J_DATABASE"
# style = "bold cyan"
# format = "db [$env_value]($style)"
