[aws]
disabled = true
symbol = " "

[battery]
disabled = true

[character]
success_symbol = "[%](bold green)"
error_symbol = "[%](bold red)"
vicmd_symbol = "[%](bold yellow)"

[dart]
symbol = " "

[directory]
read_only = "  "

[docker_context]
symbol = "  "
disabled = false
only_with_files = true

[git_branch]
# symbol = " "
symbol = ""

[gcloud]
disabled = true

[golang]
symbol = ""

[java]
disabled = true
symbol = " "

[kotlin]
disabled = true

[memory_usage]
symbol = "  "

[nodejs]
symbol = " "
disabled = true

[package]
symbol = " "
disabled = true

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = " "

[terraform]
disabled = true

# [gradle]
# disabled = true

# [env_var]
# variable = "SPRING_PROFILES_ACTIVE"
# style = "bold yellow"
# format = "using [$env_value]($style) "

# [[env_var]]
# variable = "NEO4J_DATABASE"
# style = "bold cyan"
# format = "db [$env_value]($style)"
